name: flutter_api
description: A REST API Connector, you can connect your Flutter Project to any endpoint easily.
version: 0.0.3-dev.1
repository: https://github.com/luxomansilla/flutter_api
issue_tracker: https://github.com/luxomansilla/flutter_api/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: ar.com.luxomansilla.flutter_api
        pluginClass: FlutterApiPlugin
      ios:
        pluginClass: FlutterApiPlugin
      macos:
        pluginClass: FlutterApiPlugin
      windows:
        pluginClass: FlutterApiPlugin
      linux:
        pluginClass: FlutterApiPlugin
      web:
        pluginClass: FlutterApiPlugin
        fileName: flutter_api_web.dart
