name: flutter_api
description: A REST API Connector, you can connect your Flutter Project to any endpoint easily.
version: 0.0.1
repository: https://github.com/luxomansilla/flutter_api
issue_tracker: https://github.com/luxomansilla/flutter_api/issues

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.1

flutter:  
  plugin:
    platforms:
      android:
        package: ar.com.luxomansilla.flutter_api
        pluginClass: FlutterApiPlugin
      ios:
        pluginClass: FlutterApiPlugin
      macos:
        pluginClass: FlutterApiPlugin
      windows:
        pluginClass: FlutterApiPlugin
      
      
        
    

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
